[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "thingery"
version = "0.1.0"
description = "Physical and Chemical Data Library"
readme = { file = "README.md", content-type = "text/markdown" }
license = { text = "MIT" }
authors = [{ name = "Solu Brew", email = "solubrew@solutionsbrewer.com" }]
requires-python = ">=3.10"
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Operating System :: POSIX :: Linux",
    "Operating System :: MacOS :: MacOS X",
    "Operating System :: Microsoft :: Windows",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Topic :: Utilities"]
dependencies = [
    "click>=8.0.0",
    "pyyaml>=6.0",
]

[project.scripts]
thingery = "thingery.cli:thingery_entry"

[project.urls]
Homepage = "https://www.solutionsbrewer.com/"
Changelog = "CHANGES.md"

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
where = ["."]
include = ["thingery", "thingery.*"]
exclude = [
    "test*",
    "tests*",
    "docs*",
    "examples*",
    "scripts*",
    "tools*",
]

[tool.setuptools.package-data]
thingery = [
  "**/*.yaml",
]

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py", "*_test.py"]
addopts = "-v"

[tool.ruff]
line-length = 120
